//Get all rows from expenses table.
GET http://localhost:5000/api/expenses

###

//Post a new row to expenses table.
POST http://localhost:5000/api/expenses
Content-Type: application/json

{
    "date": "2022-01-15",
    "amount": 955.00,
    "shop": "Prisma",
    "category": "testfood",
    "description": "test2"
}

###

//Delete a row from expenses table based on ID in the URL.
DELETE http://localhost:5000/api/expenses/2

###

//Update a row in expenses table based on ID in the body.
PUT http://localhost:5000/api/expenses/
Content-Type: application/json

{
    "id": 12,
    "date": "2022-12-22",
    "amount": 623.00,
    "shop": "Cittari",
    "category": "testfood333",
    "description": "testUpdated"
}

###

//Get all rows from expenses table based on month as number in the URL.
//@example: 01 = January, 02 = February, etc.
GET http://localhost:5000/api/expenses/month/01

###

//Get all rows from the expenses table based on search term in the URL.
//First term is the column name, second term is the search term.
//@example: GET http://localhost:5000/api/expenses/search?description=test
//description is the column, test is the search term.
GET http://localhost:5000/api/expenses/search?date=2022-03-18
