GET http://localhost:5000/api/expenses

###

POST http://localhost:5000/api/expenses
Content-Type: application/json

{
    "date": "2022-01-15",
    "amount": 955.00,
    "description": "test2"
}

###

DELETE http://localhost:5000/api/expenses/2

###

PUT http://localhost:5000/api/expenses/
Content-Type: application/json

{
    "id": 98,
    "date": "2022-01-15",
    "amount": 955.00,
    "description": "test2"
}

###

GET http://localhost:5000/api/expenses/month/01

###

GET http://localhost:5000/api/expenses/search?id=20

###